---
title: "Problem Set 5"
execute: 
  freeze: auto
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
```

::: {.callout-warning appearance="minimal"}
Due by 11:59 PM Wednesday April 26 via by Blackboard Assignments
:::

Please read the [instructions](https://micros23.classes.ryansafner.com/assignments/problem-sets) for completing homeworks.

<p style="text-align:center;"><a class="btn btn-primary btn-lg" target="_blank" href="/files/assignment/05-problem-set-pdf.pdf"><i class="fas fa-file-pdf"></i> Download as PDF</a> <a class="btn btn-primary btn-lg" target="_blank" href="/files/assignment/05-problem-set-docx.docx"><i class="fa-regular fa-file-word"></i> Download as .docx</a></p>

## Answers

<p style="text-align:center"><a target="_blank" href="/files/assignment/05-problem-set-answers.html"><span class="btn btn-primary btn-lg"><i class="far fa-life-ring"></i> Answers</a> <a target="_blank" href="/files/assignment/05-problem-set-answers-pdf.pdf"><span class="btn btn-primary btn-lg"><i class="fas fa-file-pdf"></i> Answers (PDF)</a> </p>

# Concepts and Critical Thinking

Please answer the following questions briefly (1-3 sentences). Use examples as necessary. Be sure to label graphs fully, if appropriate.

## Question 1

In your own words, what do (1) allocative efficiency, (2) productive efficiency, and (3) Pareto efficiency mean? Under what three conditions are markets efficient?

## Question 2

In your own words, what are the functions of market prices in society?

## Question 3

In your own words, what are transaction costs, and how do they affect exchange?

## Question 4

In your own words, explain the law of one price. *Why* would we expect it to be true (i.e. what market processes push us towards the predicted outcome)? What might *prevent* the same goods from being exchanged at the same price? [Hint: Think about your answer to the previous question!]

## Question 5

In your own words, explain what entrepreneurship is, and how it affects market prices. 

## Question 6

In your own words, explain what consumer surplus and producer surplus mean. If Ann is willing to pay up to <span>&#36;</span>6,000 for a used car, but buys it at a market price of <span>&#36;</span>2,000, what is her consumer surplus? What is the producer's surplus for Bob, who sells Ann the car for <span>&#36;</span>2,000, but would be willing to go as low as <span>&#36;</span>1,000?

## Question 7

In your own words, explain why consumers who have *less* elastic demand earn *greater* consumer surplus.

## Question 8

In your own words, explain what an externality is. Give an example, and draw a graph — either for a negative externality or a positive externality. Explain some possible ways that the problem can be solved.

## Question 9

In your own words, explain what a public good is, and give an example. Explain why markets face problems providing public goods.

## Question 10

In your own words, explain the “nirvana fallacy” and provide an example.

# Problems

Show all work for calculations. You may lose points, even if correct, for missing work. Be sure to label graphs fully, if appropriate.

## Question 11

The Ministry of Tourism in the Republic of Palau estimates that the monthly supply and demand for its scuba diving tours are: 
$$\begin{align*}
	q_S&=30p-2000\\
	q_D&=6000-20p\\	
	\end{align*}$$
> where quantity represents the number of individual dives each month and $p$ is the price of a two-tank dive.

### Part A
Calculate the equilibrium quantity and price ($q^*,p^*)$.

### Part B
Calculate the consumer surplus received by divers visiting Palau, and the producer surplus received by the dive ships. 

### Part C
Calculate the price elasticity of demand at equilibrium. Is it relatively elastic or inelastic?

### Part D
Calculate the price elasticity of supply at equilibrium. Is it relatively elastic or inelastic?

### Part E
Who earns more surplus, consumers or producers, and why?

### Part F
Suppose that the demand for scuba diving services increases, and that the new demand curve is given by $q_D'=7,000-20P$. Calculate the impact of this change in demand on the consumer surplus and producer surplus.

### Part G
Draw a well-labelled graph of all that you found in this question (label prices, quantities, surpluses, curves, etc).

## Question 12

The market for hotel rooms in a small town is characterized by the following equations:

$$\begin{align*}
q_D&=200-0.4p\\
q_S&=0.8p-40\\ \end{align*}$$

### Part A
Calculate the equilibrium price and quantity.

### Part B
Calculate the price elasticity of demand and price elasticity of supply in equilibrium. Is each relatively elastic or inelastic?

### Part C
Calculate the consumer and producer surplus in equilibrium. Who gets more surplus, and why?

### Part D
Suppose the local government sets a price ceiling on the price of hotel rooms - saying they can charge no more than $150/night. At $150, how many hotel rooms do consumers want to rent, and how many rooms do the hotels want to rent out? What is this situation?

### Part E
Explain what would happen as a result of part D if the price were allowed to change.

### Part F
The price cannot change because of the price control. Hotels will only rent out the quantity you found in part D. Calculate consumer surplus and producer surplus at this price and quantity. Compare it to your answer in part C, what has changed?

### Part G
Due to the situation created, how do you think those hotel rooms will be allocated and why? [Hint: Think about the example we did with COVID.]
